### ISSUE TITLE
Open Data Handbook media

### ISSUE THREAD

**Issue by Stephen-Gates** [okfn/ok-media#1]
The Open Data Handbook is a major project of Open Knowledge but does not appear to have a collection of icons. Some exist in the [Handbook repo](https://github.com/okfn/opendatahandbook) but they are not the same style as the others found in this repo.

**Comment by jgkim** [comment]
@Stephen-Gates As far as I know, there is no clear guidelines for project logos, and since the Open Data Handbook is a project not a working group, it doesn't have its own logo except an icon for iOS.

I am not sure, but maybe @smth could somehow help this issue. ;)

**Comment by smth** [comment]
A collection of icons for what purpose?

**Comment by Stephen-Gates** [comment]
I was adding an icon to ok forum categories but their wasn't one for the handbook in a style based on the ok logo.

**Comment by smth** [comment]
OK, as part of a logo. I'm with you. There are many projects at Open Knowledge that do not share the branding. It was, I believe, the intention of the branding agency, for all projects have a similar logo, but this seems to have been ignored / rejected across the board. I suggest you use the icon that you both referred to https://raw.githubusercontent.com/okfn/opendatahandbook/gh-pages/apple-touch-icon.png
